# Cloud Build configuration for automatic deployment with optimized caching
#
# Key optimizations:
# 1. Kaniko for Docker layer caching (reuses cached layers across builds)
# 2. Parallel push operations
# 3. Combined deploy steps where possible
#
# To enable auto-deploy on merge to main, create a trigger in GCP Console:
#   1. Go to Cloud Build > Triggers
#   2. Click "Create Trigger"
#   3. Name: "deploy-on-main-merge"
#   4. Event: "Push to a branch"
#   5. Source: Select your repository
#   6. Branch: ^main$ (regex)
#   7. Configuration: Cloud Build configuration file (this file)
#   8. Click "Create"
#
# Or use gcloud CLI:
#   gcloud builds triggers create github \
#     --repo-name=crowdit-mcp-server \
#     --repo-owner=chrisgermon \
#     --branch-pattern="^main$" \
#     --build-config=cloudbuild.yaml \
#     --name="deploy-on-main-merge"

steps:
  # Build with Kaniko for layer caching
  # Kaniko caches layers in Artifact Registry, dramatically speeding up subsequent builds
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build'
    args:
      - '--dockerfile=Dockerfile'
      - '--context=dir://.'
      - '--destination=australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:$BUILD_ID'
      - '--destination=australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:latest'
      # Enable layer caching - cache stored in Artifact Registry
      - '--cache=true'
      - '--cache-ttl=168h'
      - '--cache-repo=australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server-cache'
      # Optimize for faster builds
      - '--snapshot-mode=redo'
      - '--use-new-run'
      # Build args for reproducibility
      - '--build-arg=BUILDKIT_INLINE_CACHE=1'

  # Deploy to Cloud Run
  # Note: --remove-secrets is included in the deploy step to ensure the new image
  # and secret changes are applied atomically. Running remove-secrets separately
  # would create an intermediate revision with the old image but without secrets,
  # which could fail health checks.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crowdit-mcp-server'
      - '--image'
      - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:$BUILD_ID'
      - '--region'
      - 'australia-southeast1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--concurrency=80'
      - '--min-instances=0'
      - '--max-instances=3'
      - '--cpu-boost'
      - '--set-env-vars=BIGQUERY_PROJECT_ID=$PROJECT_ID,BIGQUERY_JOB_PROJECT_ID=$PROJECT_ID,BIGQUERY_DATA_PROJECT_ID=vision-radiology'
      - '--remove-secrets=BIGQUERY_PROJECT_ID,BIGQUERY_JOB_PROJECT_ID,SHAREPOINT_CLIENT_ID,SHAREPOINT_CLIENT_SECRET,SHAREPOINT_TENANT_ID,SHAREPOINT_REFRESH_TOKEN,FORTICLOUD_API_KEY,FORTICLOUD_API_SECRET,FORTICLOUD_CLIENT_ID,QUOTER_API_KEY'
      - '--set-secrets=HALOPSA_RESOURCE_SERVER=HALOPSA_RESOURCE_SERVER:latest,HALOPSA_AUTH_SERVER=HALOPSA_AUTH_SERVER:latest,HALOPSA_CLIENT_ID=HALOPSA_CLIENT_ID:latest,HALOPSA_CLIENT_SECRET=HALOPSA_CLIENT_SECRET:latest,HALOPSA_TENANT=HALOPSA_TENANT:latest,XERO_CLIENT_ID=XERO_CLIENT_ID:latest,XERO_CLIENT_SECRET=XERO_CLIENT_SECRET:latest,XERO_TENANT_ID=XERO_TENANT_ID:latest,XERO_REFRESH_TOKEN=XERO_REFRESH_TOKEN:latest,QUOTER_CLIENT_ID=QUOTER_CLIENT_ID:latest,QUOTER_CLIENT_SECRET=QUOTER_CLIENT_SECRET:latest,VISIONRAD_HOSTNAME=VISIONRAD_HOSTNAME:latest,VISIONRAD_USERNAME=VISIONRAD_USERNAME:latest,VISIONRAD_PRIVATE_KEY=VISIONRAD_PRIVATE_KEY:latest,SALESFORCE_INSTANCE_URL=SALESFORCE_INSTANCE_URL:latest,SALESFORCE_CLIENT_ID=SALESFORCE_CLIENT_ID:latest,SALESFORCE_CLIENT_SECRET=SALESFORCE_CLIENT_SECRET:latest,SALESFORCE_REFRESH_TOKEN=SALESFORCE_REFRESH_TOKEN:latest,N8N_API_URL=N8N_API_URL:latest,N8N_API_KEY=N8N_API_KEY:latest'
    waitFor: ['build']

images:
  - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:$BUILD_ID'
  - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  # Use higher-spec machine for faster builds
  machineType: 'E2_HIGHCPU_8'
