# Cloud Build configuration for automatic deployment
#
# To enable auto-deploy on merge to main, create a trigger in GCP Console:
#   1. Go to Cloud Build > Triggers
#   2. Click "Create Trigger"
#   3. Name: "deploy-on-main-merge"
#   4. Event: "Push to a branch"
#   5. Source: Select your repository
#   6. Branch: ^main$ (regex)
#   7. Configuration: Cloud Build configuration file (this file)
#   8. Click "Create"
#
# Or use gcloud CLI:
#   gcloud builds triggers create github \
#     --repo-name=crowdit-mcp-server \
#     --repo-owner=chrisgermon \
#     --branch-pattern="^main$" \
#     --build-config=cloudbuild.yaml \
#     --name="deploy-on-main-merge"

steps:
  # Build the container image (--no-cache ensures latest code is always used)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/crowdit-mcp-server:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/crowdit-mcp-server:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crowdit-mcp-server:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crowdit-mcp-server:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crowdit-mcp-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crowdit-mcp-server:$COMMIT_SHA'
      - '--region'
      - 'australia-southeast1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300'
      - '--concurrency=80'
      - '--min-instances=0'
      - '--max-instances=3'
      - '--set-env-vars=BIGQUERY_PROJECT_ID=$PROJECT_ID,BIGQUERY_JOB_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets=HALOPSA_RESOURCE_SERVER=HALOPSA_RESOURCE_SERVER:latest'
      - '--set-secrets=HALOPSA_AUTH_SERVER=HALOPSA_AUTH_SERVER:latest'
      - '--set-secrets=HALOPSA_CLIENT_ID=HALOPSA_CLIENT_ID:latest'
      - '--set-secrets=HALOPSA_CLIENT_SECRET=HALOPSA_CLIENT_SECRET:latest'
      - '--set-secrets=HALOPSA_TENANT=HALOPSA_TENANT:latest'
      - '--set-secrets=XERO_CLIENT_ID=XERO_CLIENT_ID:latest'
      - '--set-secrets=XERO_CLIENT_SECRET=XERO_CLIENT_SECRET:latest'
      - '--set-secrets=XERO_TENANT_ID=XERO_TENANT_ID:latest'
      - '--set-secrets=XERO_REFRESH_TOKEN=XERO_REFRESH_TOKEN:latest'
      - '--set-secrets=SHAREPOINT_CLIENT_ID=SHAREPOINT_CLIENT_ID:latest'
      - '--set-secrets=SHAREPOINT_CLIENT_SECRET=SHAREPOINT_CLIENT_SECRET:latest'
      - '--set-secrets=SHAREPOINT_TENANT_ID=SHAREPOINT_TENANT_ID:latest'
      - '--set-secrets=SHAREPOINT_REFRESH_TOKEN=SHAREPOINT_REFRESH_TOKEN:latest'
      - '--set-secrets=QUOTER_API_KEY=QUOTER_API_KEY:latest'
      - '--set-secrets=FORTICLOUD_API_KEY=FORTICLOUD_API_KEY:latest'
      - '--set-secrets=FORTICLOUD_API_SECRET=FORTICLOUD_API_SECRET:latest'
      - '--set-secrets=FORTICLOUD_CLIENT_ID=FORTICLOUD_CLIENT_ID:latest'

images:
  - 'gcr.io/$PROJECT_ID/crowdit-mcp-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/crowdit-mcp-server:latest'

options:
  logging: CLOUD_LOGGING_ONLY
