# Cloud Build configuration for automatic deployment
#
# To enable auto-deploy on merge to main, create a trigger in GCP Console:
#   1. Go to Cloud Build > Triggers
#   2. Click "Create Trigger"
#   3. Name: "deploy-on-main-merge"
#   4. Event: "Push to a branch"
#   5. Source: Select your repository
#   6. Branch: ^main$ (regex)
#   7. Configuration: Cloud Build configuration file (this file)
#   8. Click "Create"
#
# Or use gcloud CLI:
#   gcloud builds triggers create github \
#     --repo-name=crowdit-mcp-server \
#     --repo-owner=chrisgermon \
#     --branch-pattern="^main$" \
#     --build-config=cloudbuild.yaml \
#     --name="deploy-on-main-merge"

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:$BUILD_ID', '-t', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:latest', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:latest']

  # Remove old secret bindings that are now env vars (separate step due to gcloud flag restrictions)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'crowdit-mcp-server'
      - '--region'
      - 'australia-southeast1'
      - '--remove-secrets=BIGQUERY_PROJECT_ID,BIGQUERY_JOB_PROJECT_ID,SHAREPOINT_CLIENT_ID,SHAREPOINT_CLIENT_SECRET,SHAREPOINT_TENANT_ID,SHAREPOINT_REFRESH_TOKEN,FORTICLOUD_API_KEY,FORTICLOUD_API_SECRET,FORTICLOUD_CLIENT_ID'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crowdit-mcp-server'
      - '--image'
      - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:$BUILD_ID'
      - '--region'
      - 'australia-southeast1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300'
      - '--concurrency=80'
      - '--min-instances=0'
      - '--max-instances=3'
      - '--set-env-vars=BIGQUERY_PROJECT_ID=$PROJECT_ID,BIGQUERY_JOB_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets=HALOPSA_RESOURCE_SERVER=HALOPSA_RESOURCE_SERVER:latest,HALOPSA_AUTH_SERVER=HALOPSA_AUTH_SERVER:latest,HALOPSA_CLIENT_ID=HALOPSA_CLIENT_ID:latest,HALOPSA_CLIENT_SECRET=HALOPSA_CLIENT_SECRET:latest,HALOPSA_TENANT=HALOPSA_TENANT:latest,XERO_CLIENT_ID=XERO_CLIENT_ID:latest,XERO_CLIENT_SECRET=XERO_CLIENT_SECRET:latest,XERO_TENANT_ID=XERO_TENANT_ID:latest,XERO_REFRESH_TOKEN=XERO_REFRESH_TOKEN:latest,QUOTER_API_KEY=QUOTER_API_KEY:latest'

images:
  - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:$BUILD_ID'
  - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/crowdit/crowdit-mcp-server:latest'

options:
  logging: CLOUD_LOGGING_ONLY

