// Predefined form template matching the spreadsheet structure
export interface FormField {
  name: string;
  type: "text" | "boolean" | "select" | "date" | "textarea" | "url" | "file" | "number" | "address" | "currency";
  options?: string[];
  placeholder?: string;
  description?: string;
  hasFileUpload?: boolean; // Allow file attachment for this field
  columns?: string[]; // For table-like entries (e.g., equipment details)
}

export interface FormSection {
  name: string;
  owner: string;
  fields: FormField[];
}

export const CLINIC_SETUP_FORM_TEMPLATE: FormSection[] = [
  {
    name: "Entity Setup",
    owner: "Mays",
    fields: [
      { name: "Trading Name", type: "text", placeholder: "e.g., Quantum Medical Imaging Victoria Point" },
      { name: "Entity Name", type: "text", placeholder: "e.g., Victoria Point Medical Imaging Pty Ltd" },
      { name: "Business Name Registered", type: "boolean" },
      { name: "ACN", type: "text", placeholder: "e.g., 688 901 519" },
      { name: "ABN", type: "text", placeholder: "e.g., 73 688 901 519" },
      { name: "Business Address", type: "address", placeholder: "Start typing to search..." },
      { name: "Phone", type: "text", placeholder: "e.g., 07 2809 1511" },
      { name: "Fax", type: "text", placeholder: "e.g., 07 2809 1512" },
      { name: "ASIC Key", type: "boolean" },
      { name: "Business Insurance (PL & Glass CoC)", type: "text", hasFileUpload: true, description: "Public Liability and Glass Certificate of Currency" },
      { name: "Work Cover", type: "text", hasFileUpload: true },
      { name: "Xero (Payroll/Accounts)", type: "text" },
      { name: "Bank Guarantee", type: "boolean" },
      { name: "Teammed (Documents sent to Sam)", type: "boolean" },
      { name: "Teammed Account Setup", type: "boolean" },
      { name: "EFTPOS Terminal (Document sent to Kellie)", type: "boolean" },
      { name: "Bank Set Up", type: "boolean" },
      { name: "Send details to MLO for new clinic", type: "boolean" },
      { name: "Clinic Security", type: "text" },
    ],
  },
  {
    name: "Lease",
    owner: "Mays/Mustafa/Nabeel",
    fields: [
      { name: "Clinic Keys", type: "text" },
      { name: "Lock Box Code", type: "text" },
      { name: "Lease Commencement Date", type: "date" },
      { name: "Lease Document", type: "file" },
    ],
  },
  {
    name: "Building Info",
    owner: "Mustafa",
    fields: [
      { name: "Building Construction Start Date", type: "date" },
      { name: "Clinic Plan Reviewed", type: "boolean", description: "Reviewed by Nabeel and Mushi" },
      { name: "Clinic Plan Document", type: "file" },
      { name: "Machines Ordered (Email sent to Mushi)", type: "boolean", description: "US | CT | DEXA | X-ray | OPG | MRI - Email template requesting serial numbers" },
      { name: "CT Plan", type: "select", options: ["Canon", "Siemens", "N/A"] },
      { name: "CT Serial Number Obtained", type: "boolean" },
      { name: "X-ray/OPG Plan", type: "select", options: ["Shimadzu", "Fuji", "N/A"] },
      { name: "X-ray Serial Number Obtained", type: "boolean" },
      { name: "DEXA Plan", type: "select", options: ["Inmed", "Hologic", "N/A"] },
      { name: "DEXA Serial Number Obtained", type: "boolean" },
      { name: "Mammogram Plan", type: "select", options: ["Hologic", "Siemens", "Fuji", "N/A"] },
      { name: "Mammogram Serial Number Obtained", type: "boolean" },
      { name: "Ultrasound Vendor", type: "select", options: ["Canon", "GE", "Phillips", "N/A"] },
      { name: "Ultrasound Quantity", type: "select", options: ["1", "2", "3", "4"] },
      { name: "Ultrasound Serial Number Obtained", type: "boolean" },
      { name: "MRI Plan", type: "select", options: ["Siemens", "N/A"] },
      { name: "MRI Serial Number Obtained", type: "boolean" },
      { name: "Rad Test Plans", type: "text", hasFileUpload: true },
    ],
  },
  {
    name: "Lead + Fire Safety",
    owner: "Mustafa/Nabeel/Mays",
    fields: [
      { name: "Lead Glass", type: "boolean", hasFileUpload: true },
      { name: "Lead Glass Supplier", type: "text" },
      { name: "Lead Glass Notes", type: "textarea", description: "Invoice details, collection dates, specifications" },
      { name: "Lead Rolls", type: "boolean", hasFileUpload: true },
      { name: "Lead Rolls Supplier", type: "text" },
      { name: "Lead Rolls Notes", type: "textarea", description: "Size specifications, weight, collection details" },
      { name: "Fire Safety Check", type: "boolean", hasFileUpload: true },
    ],
  },
  {
    name: "Building Contractor Details",
    owner: "Mustafa",
    fields: [
      { name: "Builder Contact Details", type: "textarea", placeholder: "Name, Phone, Email" },
      { name: "Cabinetry Contact Details", type: "textarea" },
      { name: "Electrician Contact Details", type: "textarea" },
      { name: "Painter Contact Details", type: "textarea" },
      { name: "Plumber Contact Details", type: "textarea" },
      { name: "A/C Unit Contact Details", type: "textarea" },
      { name: "Signage Contact Details", type: "textarea" },
      { name: "Curtains Contact Details", type: "textarea" },
    ],
  },
  {
    name: "Electrical Setup",
    owner: "Mays",
    fields: [
      { name: "Connect Clinic to Provider", type: "text", placeholder: "e.g., AGL, Embedded Network" },
      { name: "Connection Date", type: "date" },
      { name: "Utilities Supplier", type: "text", placeholder: "e.g., Business Smart Saver Plan" },
      { name: "Account Number", type: "text" },
      { name: "NMI", type: "textarea", placeholder: "NMI number(s) - can be multiple" },
      { name: "Contact Email", type: "text" },
      { name: "Contact Phone Number", type: "text" },
    ],
  },
  {
    name: "Start Up",
    owner: "Nabeel/Danni",
    fields: [
      { name: "Worksite/Workstation Licence (Kestral)", type: "boolean", description: "Obtained from Kestral" },
      { name: "LSPN Obtained", type: "boolean", hasFileUpload: true },
      { name: "Radiation Licence Applied", type: "boolean" },
      { name: "Radiation Licence Received", type: "boolean", hasFileUpload: true, description: "FINAL licence received" },
      { name: "Accreditation Completed", type: "boolean", hasFileUpload: true },
      { name: "Kestral Setup", type: "boolean" },
      { name: "Equipment Added to VRG Master Spreadsheet", type: "boolean", description: "Check with Mushi" },
    ],
  },
  {
    name: "Equipment",
    owner: "Nabeel",
    fields: [
      { name: "X-Ray Manufacturer", type: "text", placeholder: "e.g., Shimadzu Medical" },
      { name: "X-Ray Model", type: "text", placeholder: "e.g., RADspeed Pro" },
      { name: "X-Ray Serial Number", type: "text" },
      { name: "X-Ray kV/mA", type: "text" },
      { name: "X-Ray ETA", type: "date" },
      { name: "X-Ray Delivered", type: "boolean" },
      { name: "X-Ray Plans/Quote", type: "file" },
      { name: "X-Ray Tube Details", type: "textarea" },
      { name: "OPG Manufacturer", type: "text" },
      { name: "OPG Model", type: "text" },
      { name: "OPG Serial Number", type: "text" },
      { name: "OPG Delivered", type: "boolean" },
      { name: "OPG Plans/Quote", type: "file" },
      { name: "Ultrasound 1 Manufacturer", type: "text", placeholder: "e.g., Canon" },
      { name: "Ultrasound 1 Model", type: "text", placeholder: "e.g., i700" },
      { name: "Ultrasound 1 Serial Number", type: "text" },
      { name: "Ultrasound 1 Delivered", type: "boolean" },
      { name: "Ultrasound 2 Manufacturer", type: "text" },
      { name: "Ultrasound 2 Model", type: "text" },
      { name: "Ultrasound 2 Serial Number", type: "text" },
      { name: "Ultrasound 2 Delivered", type: "boolean" },
      { name: "Ultrasound 3 Details", type: "textarea", hasFileUpload: true },
      { name: "Ultrasound 4 Details", type: "textarea", hasFileUpload: true },
      { name: "Elastography Details", type: "textarea", hasFileUpload: true },
      { name: "CT Manufacturer", type: "text", placeholder: "e.g., Siemens Healthcare" },
      { name: "CT Model", type: "text", placeholder: "e.g., Somatom go.Top" },
      { name: "CT Serial Number", type: "text" },
      { name: "CT kV/mA", type: "text", placeholder: "e.g., 140 kV / 825 mA" },
      { name: "CT Delivered", type: "boolean" },
      { name: "CT Plans/Quote", type: "file" },
      { name: "CT Tube Details", type: "textarea" },
      { name: "MRI Manufacturer", type: "text" },
      { name: "MRI Model", type: "text" },
      { name: "MRI Serial Number", type: "text" },
      { name: "MRI Delivered", type: "boolean" },
      { name: "MRI Plans/Quote", type: "file" },
      { name: "Mammogram Manufacturer", type: "text" },
      { name: "Mammogram Model", type: "text" },
      { name: "Mammogram Serial Number", type: "text" },
      { name: "Mammogram Delivered", type: "boolean" },
      { name: "DEXA Details", type: "textarea", hasFileUpload: true, description: "Include Scanner S/N, Tube Housing, Model details" },
      { name: "DEXA Delivered", type: "boolean" },
      { name: "Contrast Warmer", type: "text", hasFileUpload: true },
      { name: "Injector", type: "text", hasFileUpload: true },
      { name: "Lumicare", type: "text", hasFileUpload: true },
    ],
  },
  {
    name: "Staff",
    owner: "",
    fields: [
      { name: "Receptionist", type: "textarea", placeholder: "Name, Contact, Start Date" },
      { name: "Radiographer - X-Ray", type: "textarea" },
      { name: "Radiographer - CT", type: "textarea" },
      { name: "Radiographer - MRI", type: "textarea" },
      { name: "Sonographer", type: "textarea" },
      { name: "Marketing Contact", type: "textarea" },
      { name: "Seek Ads Posted", type: "boolean" },
    ],
  },
  {
    name: "Reception/Setup Items",
    owner: "Mustafa/Mays/Danni",
    fields: [
      { name: "IT Equipment Ordered", type: "boolean" },
      { name: "IT Equipment Details", type: "textarea", placeholder: "Quantity, Supplier, ETA, Cost", hasFileUpload: true },
      { name: "Radiologist Chair", type: "boolean" },
      { name: "Radiologist Desk 1500/1800mm", type: "boolean" },
      { name: "Sono/CT/Receptionist Chairs (Highback)", type: "boolean" },
      { name: "CT Blanket", type: "boolean" },
      { name: "Change Room Baskets", type: "boolean" },
      { name: "Ultrasound Beds", type: "boolean" },
      { name: "CT Trolley (Emergency)", type: "boolean", description: "From Medshop" },
      { name: "CT Euflexxa Fridge", type: "boolean" },
      { name: "CT Warmer", type: "boolean" },
      { name: "CT Water Jugs", type: "boolean" },
      { name: "Trolley Single (U/S rooms)", type: "boolean" },
      { name: "Trolley Double (CT cannulate)", type: "boolean" },
      { name: "Kimberley Clarke Roll Holders", type: "boolean" },
      { name: "Stool Gas Lift", type: "boolean" },
      { name: "Saddle Stool", type: "boolean" },
      { name: "TV 55\"/65\"", type: "boolean" },
      { name: "TV Console", type: "boolean" },
      { name: "TV 43\"", type: "boolean" },
      { name: "Wheelchair", type: "boolean", description: "Can be ordered via Teammed" },
      { name: "Medical Scales", type: "boolean" },
      { name: "Glove Holders (All Rooms)", type: "text", placeholder: "Quantity, Order ref" },
      { name: "Pillows - Foam (Medium & Low Profile)", type: "boolean" },
      { name: "Sanitiser Wall Mount/Brackets", type: "text", placeholder: "Quantity, Order ref" },
      { name: "Water Cooler", type: "boolean" },
      { name: "Kids Corner (Table & Games)", type: "boolean" },
      { name: "Decoration (Art/Plants)", type: "boolean" },
      { name: "X-Ray Sponges & TV Sponge", type: "boolean" },
      { name: "Safe", type: "boolean", hasFileUpload: true },
      { name: "Petty Cash Setup", type: "boolean" },
      { name: "Markers", type: "boolean" },
      { name: "Lead Apron", type: "boolean" },
      { name: "Anaphylaxis/Hand Wash/Pregnancy Posters", type: "boolean" },
      { name: "Double Step", type: "boolean" },
      { name: "Sandbags", type: "boolean" },
      { name: "Brochure Holder", type: "boolean" },
      { name: "Waiting Room Chairs", type: "boolean" },
    ],
  },
  {
    name: "Marketing",
    owner: "Nabeel/Lauren",
    fields: [
      { name: "Pamphlets Ordered", type: "boolean", hasFileUpload: true },
      { name: "Contact Details Card", type: "boolean", hasFileUpload: true },
      { name: "Registered on Health Engine", type: "boolean" },
      { name: "Facebook Registration", type: "boolean" },
      { name: "Facebook Page URL", type: "url" },
      { name: "LinkedIn Registration", type: "boolean" },
      { name: "LinkedIn Page URL", type: "url" },
      { name: "Photographs Taken", type: "boolean", hasFileUpload: true },
      { name: "Walkthrough Video", type: "boolean", hasFileUpload: true },
    ],
  },
  {
    name: "Officeworks Order",
    owner: "Mays",
    fields: [
      { name: "Order Spreadsheet/List", type: "file" },
      { name: "Order Status", type: "select", options: ["Not Started", "Ordered", "Partially Received", "Fully Received"] },
      { name: "Desktop File Organiser 5 Drawer", type: "text", placeholder: "Qty" },
      { name: "Large Tape Dispenser", type: "boolean" },
      { name: "Document Tray 3 Pack", type: "boolean" },
      { name: "Mesh Pencil Cup", type: "text", placeholder: "Qty" },
      { name: "Business Card Holder", type: "text", placeholder: "Qty" },
      { name: "Paper Clip Holder", type: "text", placeholder: "Qty" },
      { name: "2 Hole Punch", type: "boolean" },
      { name: "Correction Tape", type: "text", placeholder: "Qty" },
      { name: "Staples 26/6", type: "text", placeholder: "Qty packs" },
      { name: "Clear Tape Rolls", type: "text", placeholder: "Qty" },
      { name: "Tuff Tack", type: "boolean" },
      { name: "Sharpie Permanent Marker", type: "text", placeholder: "Qty" },
      { name: "Highlighters Assorted Pack", type: "boolean" },
      { name: "Postage Stamps", type: "text", placeholder: "Qty packs" },
      { name: "Flat Files (Blue/Black/Red)", type: "boolean" },
      { name: "A4 Clipboard Clear", type: "text", placeholder: "Qty" },
      { name: "Wall Pocket Portrait", type: "text", placeholder: "Qty" },
      { name: "Label Maker", type: "boolean" },
      { name: "Label Tape", type: "text", placeholder: "Qty packs" },
      { name: "Full Strip Stapler", type: "text", placeholder: "Qty" },
      { name: "Paper Clips Assorted", type: "boolean" },
      { name: "Stainless Steel Ruler 30cm", type: "text", placeholder: "Qty" },
      { name: "A5 Office Pad Ruled", type: "text", placeholder: "Qty" },
      { name: "Eraser", type: "boolean" },
      { name: "Mini Cash Box", type: "boolean" },
      { name: "Student Scissors", type: "text", placeholder: "Qty" },
      { name: "A4 Copy Paper Carton", type: "text", placeholder: "Qty" },
      { name: "Magazine File 3 Pack", type: "boolean" },
      { name: "Garbage Bags 56L", type: "text", placeholder: "Qty packs" },
      { name: "Kitchen Tidy Bags", type: "text", placeholder: "Qty packs" },
      { name: "Cork Board", type: "boolean" },
      { name: "Push Pins", type: "boolean" },
      { name: "Ballpoint Pens Assorted", type: "boolean" },
      { name: "Ballpoint Pens Black Pack", type: "boolean" },
      { name: "Swing Bin 50L", type: "text", placeholder: "Qty" },
      { name: "Bullet Bin 25L", type: "text", placeholder: "Qty" },
      { name: "Mesh Bin 18L", type: "boolean" },
      { name: "A4 Organiser Basket", type: "text", placeholder: "Qty" },
      { name: "Coloured A4 Clipboards", type: "text", placeholder: "Qty each colour" },
      { name: "Bulldog Clips", type: "text", placeholder: "Qty packs" },
      { name: "Graphite Pencils HB Pack", type: "boolean" },
      { name: "A4 Laminator", type: "boolean" },
      { name: "Laminating Pouches A4", type: "text", placeholder: "Qty packs" },
      { name: "AAA Batteries Pack", type: "boolean" },
      { name: "AA Batteries Pack", type: "boolean" },
      { name: "Mouse Pad", type: "text", placeholder: "Qty" },
      { name: "Wall Display Panel", type: "boolean" },
      { name: "Scientific Calculator", type: "boolean" },
      { name: "Wire Paper Spike", type: "boolean" },
      { name: "Sticky Notes Value Pack", type: "boolean" },
      { name: "Flags Assorted Pack", type: "boolean" },
      { name: "Staple Remover", type: "boolean" },
      { name: "Magnet Clips Pack", type: "boolean" },
      { name: "Stickers (Kids)", type: "boolean" },
      { name: "Order Total Cost", type: "currency" },
      { name: "Order Notes", type: "textarea" },
    ],
  },
  {
    name: "Kitchen Order",
    owner: "Mays",
    fields: [
      { name: "Fridge", type: "boolean" },
      { name: "Coffee Machine", type: "text", placeholder: "Brand/Model", hasFileUpload: true },
      { name: "Milk Jug", type: "boolean" },
      { name: "Microwave", type: "boolean" },
      { name: "Glasses", type: "boolean" },
      { name: "Coffee Mugs", type: "boolean" },
      { name: "Cutlery", type: "boolean" },
      { name: "Cutlery Tray", type: "boolean" },
      { name: "Dish Rack", type: "boolean" },
      { name: "Tea Towels", type: "boolean" },
      { name: "Dinner Set", type: "boolean" },
      { name: "Canisters", type: "boolean" },
      { name: "Vacuum (Dyson)", type: "boolean" },
      { name: "Toaster/Kettle", type: "boolean" },
      { name: "Sandwich Press", type: "boolean" },
      { name: "Table/Chairs", type: "boolean" },
      { name: "Nescafe Coffee", type: "boolean" },
      { name: "Tea (English, Black, Peppermint)", type: "boolean" },
      { name: "Sauces (Tomato, BBQ, Mayo)", type: "boolean" },
      { name: "Container for Jelly Beans", type: "boolean" },
      { name: "Jelly Beans", type: "boolean" },
      { name: "Dish Washing Soap", type: "boolean" },
      { name: "Chux", type: "boolean" },
      { name: "UHT Milk (Almond, Soy, Full, Light)", type: "boolean" },
      { name: "Pepper", type: "boolean" },
      { name: "Salt", type: "boolean" },
      { name: "Sugar", type: "boolean" },
      { name: "Kitchen Notes", type: "textarea" },
    ],
  },
  {
    name: "Bunnings Order",
    owner: "Mays/Danni",
    fields: [
      { name: "Bunnings Order Reference", type: "text" },
      { name: "Microfibre Cloths", type: "boolean" },
      { name: "Spray and Wipe", type: "boolean" },
      { name: "Wall Hooks", type: "text", placeholder: "Qty - for gowns, bags" },
      { name: "Coat Rack", type: "text", placeholder: "Qty" },
      { name: "Storage + Key Safe", type: "boolean" },
      { name: "Extension Cord", type: "boolean" },
      { name: "Plastic Storage Tote Size 50", type: "text", placeholder: "Qty" },
      { name: "Plastic Storage Tote Size 30", type: "text", placeholder: "Qty" },
      { name: "Plastic Storage Tote Size 20", type: "text", placeholder: "Qty" },
      { name: "Backing Plate for Containers", type: "text", placeholder: "Qty" },
      { name: "Order Notes", type: "textarea" },
    ],
  },
  {
    name: "Toilet",
    owner: "Mays",
    fields: [
      { name: "Soap Dispensers", type: "text", placeholder: "Quantity" },
      { name: "Kleenex Hand Optimum Dispenser", type: "text", placeholder: "Quantity" },
      { name: "Toilet Roll Holders", type: "text", placeholder: "Quantity" },
      { name: "Toilet Brushes", type: "text", placeholder: "Quantity" },
    ],
  },
  {
    name: "Medical Equipment",
    owner: "Slav",
    fields: [
      { name: "Surgeon Stool Black Vinyl", type: "text", placeholder: "Qty" },
      { name: "Step Up Stool Double S/Steel", type: "text", placeholder: "Qty" },
      { name: "Oximeter SPO2", type: "boolean" },
      { name: "Height Measure Wall Mount", type: "boolean" },
      { name: "Measuring Tape", type: "boolean" },
      { name: "Stethoscope (Littmann Classic III)", type: "boolean", hasFileUpload: true },
      { name: "AED Defibrillator (IPAD CU-SP1)", type: "boolean", hasFileUpload: true },
      { name: "Defibrillator Adult Pads", type: "boolean" },
      { name: "Defibrillator Paediatric Pads", type: "boolean" },
      { name: "Defibrillator Battery", type: "boolean" },
      { name: "Defibrillator Wall Cabinet", type: "boolean" },
      { name: "Nebuliser (Speedymed)", type: "boolean" },
      { name: "Nebuliser Kit Adult", type: "boolean" },
      { name: "Nebuliser Kit Child", type: "boolean" },
      { name: "Pulse Oximeter Fingertip", type: "boolean" },
      { name: "First Aid Kit", type: "boolean" },
      { name: "Vital Signs Monitor NIBP/SPO2", type: "boolean" },
      { name: "Vital Signs Monitor Trolley", type: "boolean" },
      { name: "Blood Collection Chair Black", type: "boolean" },
    ],
  },
  {
    name: "Medical Consumables - Clinical Products",
    owner: "Danni",
    fields: [
      { name: "Order List/Spreadsheet", type: "file" },
      { name: "Order Status", type: "select", options: ["Not Started", "Ordered", "Partially Received", "Fully Received"] },
      { name: "Powder Coated Trolley 2 Drawer", type: "text", placeholder: "Qty" },
      { name: "Treatment Trolley 3 Drawer", type: "boolean" },
      { name: "S/S Trolley 2 Drawer Side by Side", type: "boolean" },
      { name: "Saddle Stool Black Vinyl", type: "boolean" },
    ],
  },
  {
    name: "Medical Consumables - Sterile Gloves",
    owner: "Danni",
    fields: [
      { name: "Protexis Gloves P/Free Size 6.0", type: "text", placeholder: "Qty boxes" },
      { name: "Protexis Gloves P/Free Size 6.5", type: "text", placeholder: "Qty boxes" },
      { name: "Protexis Gloves P/Free Size 7.5", type: "text", placeholder: "Qty boxes" },
      { name: "Protexis Gloves P/Free Size 8.0", type: "text", placeholder: "Qty boxes" },
      { name: "Protexis Gloves P/Free Size 8.5", type: "text", placeholder: "Qty boxes" },
      { name: "Dermaclean Gloves Small", type: "text", placeholder: "Qty boxes" },
      { name: "Dermaclean Gloves Medium", type: "text", placeholder: "Qty boxes" },
      { name: "Dermaclean Gloves Large", type: "text", placeholder: "Qty boxes" },
      { name: "Nitratex Gloves Medium", type: "text", placeholder: "Qty boxes" },
    ],
  },
  {
    name: "Medical Consumables - Wound Dressing",
    owner: "Danni",
    fields: [
      { name: "Leukoplast Universal Sterile 19x72mm", type: "text", placeholder: "Qty boxes" },
      { name: "Tegaderm Pad 5x7cm", type: "text", placeholder: "Qty boxes" },
      { name: "IV Pressure Pad Nichiban", type: "text", placeholder: "Qty boxes" },
      { name: "Cotton Balls Sterile 5s", type: "text", placeholder: "Qty packets" },
      { name: "Micropore + Dispenser 25mm", type: "text", placeholder: "Qty boxes" },
      { name: "Transpore Tape 25mm", type: "text", placeholder: "Qty boxes" },
      { name: "Compose Island Dressing 7.5x5cm", type: "text", placeholder: "Qty boxes" },
      { name: "Micropore 12mm", type: "text", placeholder: "Qty boxes" },
      { name: "Gauze Square 7.5x7.5cm", type: "text", placeholder: "Qty boxes" },
      { name: "Plastic Adhesive Strips", type: "boolean" },
      { name: "Tegaderm Film Dressing 6x7cm", type: "boolean" },
      { name: "Cotton Tips Sterile", type: "boolean" },
      { name: "Clinicrepe 7.5cm", type: "boolean" },
      { name: "Micropore Pink", type: "boolean" },
    ],
  },
  {
    name: "Medical Consumables - Infection Control",
    owner: "Danni",
    fields: [
      { name: "Alcohol Swabs Webcol 2PLY", type: "text", placeholder: "Qty boxes" },
      { name: "Isowipe Wipes", type: "text", placeholder: "Qty tubs" },
      { name: "Avagard Antiseptic Handrub 500ml", type: "text", placeholder: "Qty bottles" },
      { name: "Contaminated Waste Bags 27L", type: "text", placeholder: "Qty packets" },
      { name: "Sharps Container 1.4L", type: "text", placeholder: "Qty" },
      { name: "Sharps Container 3L", type: "text", placeholder: "Qty" },
      { name: "Drape Fenestrated W/proof 45x75cm", type: "text", placeholder: "Qty" },
      { name: "Chlorhexidine Wipes/Prep Pads", type: "boolean" },
      { name: "Clinell Universal Disinfectant Bucket", type: "text", placeholder: "Qty" },
      { name: "Microshield Handwash", type: "boolean" },
      { name: "Kleenex Hand Soap 1L", type: "text", placeholder: "Qty cartridges" },
      { name: "Viraclean Disinfectant", type: "boolean" },
    ],
  },
  {
    name: "Medical Consumables - Interventional",
    owner: "Danni",
    fields: [
      { name: "Dressing Packs Basic", type: "text", placeholder: "Qty" },
      { name: "Kidney Dish 700ml Yellow N/Strl", type: "text", placeholder: "Qty" },
      { name: "Kidney Dish 700ml Clear N/Strl", type: "text", placeholder: "Qty" },
      { name: "Steristrip 6x38mm", type: "text", placeholder: "Qty boxes" },
      { name: "Marking Pen Surgical w/Ruler", type: "text", placeholder: "Qty" },
      { name: "Freezer Bag with Rubber Band", type: "boolean" },
      { name: "Drape Fenestrated 45x60cm", type: "text", placeholder: "Qty" },
      { name: "Huck Towel Sterile", type: "text", placeholder: "Qty" },
      { name: "Scalpel Blades No.11", type: "text", placeholder: "Qty boxes" },
    ],
  },
  {
    name: "Medical Consumables - Cardiac",
    owner: "Danni",
    fields: [
      { name: "ECG Electrodes Red Dot Foam 4x3.5cm", type: "text", placeholder: "Qty packets" },
      { name: "Trace Prep Red Dot", type: "text", placeholder: "Qty rolls" },
      { name: "Razor Single Edge", type: "text", placeholder: "Qty packets" },
      { name: "ECG Electrodes with Abrader", type: "boolean" },
      { name: "Disposable Prep Razor", type: "boolean" },
    ],
  },
  {
    name: "Medical Consumables - Syringes & Needles",
    owner: "Danni",
    fields: [
      { name: "Syringe 1ml Luer Lock", type: "text", placeholder: "Qty boxes" },
      { name: "Syringe 3ml Luer Lock", type: "text", placeholder: "Qty boxes" },
      { name: "Syringe 5ml Luer Lock", type: "text", placeholder: "Qty boxes" },
      { name: "Syringe 10ml Luer Lock", type: "text", placeholder: "Qty boxes" },
      { name: "Syringe 20ml Luer Lock", type: "text", placeholder: "Qty boxes" },
      { name: "Syringe 30ml Luer Lock", type: "text", placeholder: "Qty boxes" },
      { name: "Needle Draw Up 18G x 1.5\" Blunt", type: "text", placeholder: "Qty boxes" },
      { name: "Needle 18G x 1.5\"", type: "text", placeholder: "Qty boxes" },
      { name: "Needle 19G x 38mm", type: "text", placeholder: "Qty boxes" },
      { name: "Needle 20G x 1\"", type: "text", placeholder: "Qty boxes" },
      { name: "Needle 21G x 1.5\"", type: "text", placeholder: "Qty boxes" },
      { name: "Needle 22G x 2\" Sterican", type: "text", placeholder: "Qty boxes" },
      { name: "Needle 23G x 1.25\"", type: "text", placeholder: "Qty boxes" },
      { name: "Needle 25G x 1\"", type: "text", placeholder: "Qty boxes" },
      { name: "Needle 25G x 1.5\"", type: "text", placeholder: "Qty boxes" },
      { name: "Spinal Needle 22G x 3.5\"", type: "text", placeholder: "Qty boxes" },
      { name: "Spinal Needle 22G x 5\" Quincke", type: "text", placeholder: "Qty boxes" },
      { name: "Spinal Needle 22G x 7\" Quincke", type: "text", placeholder: "Qty boxes" },
      { name: "Uniever Spinal Needles 22Gx90mm", type: "text", placeholder: "Qty" },
    ],
  },
  {
    name: "Medical Consumables - Cannulas & Tubing (CT)",
    owner: "Danni",
    fields: [
      { name: "Surflo IV Cath 18G x 1.25\"", type: "text", placeholder: "Qty" },
      { name: "Surflo IV Cath 18G x 51mm", type: "text", placeholder: "Qty" },
      { name: "Surflo IV Cath 20G x 1\"", type: "text", placeholder: "Qty" },
      { name: "Surflo IV Cath 20G x 51mm", type: "text", placeholder: "Qty" },
      { name: "Surflo IV Cath 22G x 1\"", type: "text", placeholder: "Qty" },
      { name: "Surflo IV Cath 24G x 19mm", type: "text", placeholder: "Qty" },
      { name: "Extension Tube Set 25cm", type: "text", placeholder: "Qty boxes" },
      { name: "Extension Tube Set 75cm", type: "text", placeholder: "Qty boxes" },
      { name: "Safsite Valve Injection Port", type: "text", placeholder: "Qty" },
      { name: "Giving Set Needle-Free", type: "boolean" },
    ],
  },
  {
    name: "Medical Consumables - Ultrasound",
    owner: "Danni",
    fields: [
      { name: "Condoms Lubricated", type: "text", placeholder: "Qty boxes" },
      { name: "Condoms Latex Free", type: "text", placeholder: "Qty packets" },
      { name: "Lubricating Gel 3ml Sachets", type: "text", placeholder: "Qty boxes" },
      { name: "Lubricating Gel 50g Tube", type: "boolean" },
      { name: "Ultrasound Gel 5L", type: "text", placeholder: "Qty" },
      { name: "Ultrasound Gel 250ml", type: "text", placeholder: "Qty" },
      { name: "Transeptic Cleaning Solution 250ml", type: "boolean" },
      { name: "Ultrasound Probe Cover", type: "boolean" },
    ],
  },
  {
    name: "Medical Consumables - Pharmaceuticals",
    owner: "Danni",
    fields: [
      { name: "Sodium Chloride 0.9% 10ml Injection", type: "text", placeholder: "Qty boxes" },
      { name: "Sodium Chloride 0.9% 250ml Bag", type: "text", placeholder: "Qty" },
      { name: "Sodium Chloride 0.9% 500ml Bag", type: "text", placeholder: "Qty" },
      { name: "Sodium Chloride 0.9% 1000ml Bag", type: "text", placeholder: "Qty" },
      { name: "Surgi-Prep C Pink 500ml", type: "text", placeholder: "Qty bottles" },
      { name: "Chlorhexidine 0.1% Aqueous 30ml", type: "boolean" },
      { name: "Povidone-Iodine 10% 100ml", type: "boolean" },
      { name: "Xylocaine 1% 5ml Plain", type: "text", placeholder: "Qty boxes" },
      { name: "Lignocaine 1% 5ml", type: "text", placeholder: "Qty boxes" },
      { name: "Bupivacaine 0.5% 10ml", type: "text", placeholder: "Qty boxes" },
      { name: "Depo Medrol 40mg/1ml", type: "text", placeholder: "Qty boxes" },
      { name: "Kenacort A10 10mg/1ml", type: "text", placeholder: "Qty boxes" },
      { name: "Kenacort A40 40mg/1ml", type: "text", placeholder: "Qty boxes" },
      { name: "Celestone Chronodose 5.7mg/1ml", type: "text", placeholder: "Qty boxes" },
      { name: "Dexamethasone 4mg/1ml", type: "text", placeholder: "Qty boxes" },
      { name: "Metoprolol Tablets 50mg", type: "boolean" },
    ],
  },
  {
    name: "Medical Consumables - Emergency Medications",
    owner: "Danni",
    fields: [
      { name: "Epipen 0.30mg/2ml Adult", type: "boolean" },
      { name: "Epipen Junior 0.15mg/2ml", type: "boolean" },
      { name: "Adrenaline 1:1000 1ml", type: "text", placeholder: "Qty boxes" },
      { name: "Atropine Injection 600mcg 1ml", type: "text", placeholder: "Qty boxes" },
      { name: "Glucagen Hypokit 1IU", type: "boolean" },
      { name: "Nitrolingual Spray 400mcg", type: "boolean" },
      { name: "Ventolin Inhaler Complete", type: "boolean" },
      { name: "Salbutamol 5mg/2.5ml", type: "text", placeholder: "Qty boxes" },
      { name: "Solu-Cortef 100mg 2ml", type: "boolean" },
      { name: "Solu-Cortef 250mg 2ml", type: "boolean" },
      { name: "Panadol 500mg Tablets", type: "text", placeholder: "Qty boxes" },
      { name: "Nurofen 200mg Tablets", type: "text", placeholder: "Qty boxes" },
      { name: "Zyrtec 10mg Tablets", type: "text", placeholder: "Qty boxes" },
      { name: "Telfast 180mg Tablets", type: "boolean" },
      { name: "Phenergan 10mg Tablets", type: "boolean" },
      { name: "Phenergan 25mg Tablets", type: "boolean" },
      { name: "Hirudoid Cream 14g", type: "boolean" },
    ],
  },
  {
    name: "Medical Consumables - Paper Products & Disposables",
    owner: "Danni",
    fields: [
      { name: "Face Mask Level 1 Ear Loop 3PLY", type: "text", placeholder: "Qty boxes" },
      { name: "N95 Respirator Masks", type: "boolean" },
      { name: "Toilet Tissue 2PLY", type: "text", placeholder: "Qty cartons" },
      { name: "Scott Optimum Towel", type: "text", placeholder: "Qty cartons" },
      { name: "Versa Towel", type: "text", placeholder: "Qty cartons" },
      { name: "Facial Tissue 2PLY", type: "text", placeholder: "Qty cartons" },
      { name: "Tourniquet Adult Reusable", type: "text", placeholder: "Qty" },
      { name: "Medicine Measure Cup 30ml", type: "text", placeholder: "Qty packets" },
      { name: "Denture Cups No Lid", type: "text", placeholder: "Qty packets" },
      { name: "Vomit Bags Emesis 1500ml", type: "text", placeholder: "Qty packets" },
      { name: "Pillow Protector Vinyl", type: "text", placeholder: "Qty" },
      { name: "Underpads 5PLY 55x40cm", type: "text", placeholder: "Qty cartons" },
      { name: "Plastic Cups 200ml", type: "text", placeholder: "Qty cartons" },
      { name: "Head Pads", type: "boolean" },
      { name: "Disposable Patient Gowns", type: "boolean" },
      { name: "Consumables Notes", type: "textarea" },
    ],
  },
  {
    name: "IT Setup",
    owner: "Nabeel",
    fields: [
      { name: "Network Setup", type: "text" },
      { name: "Workstations Installed", type: "number" },
      { name: "Printers Installed", type: "number" },
      { name: "PACS Integration", type: "boolean" },
      { name: "RIS Integration", type: "boolean" },
      { name: "IT Notes", type: "textarea" },
    ],
  },
  {
    name: "Phones",
    owner: "Nabeel",
    fields: [
      { name: "Phone System Provider", type: "text" },
      { name: "Number of Extensions", type: "number" },
      { name: "Main Phone Number", type: "text" },
      { name: "Fax Number", type: "text" },
      { name: "Phone System Installed", type: "boolean" },
    ],
  },
  {
    name: "Signage",
    owner: "Nabeel",
    fields: [
      { name: "External Signage", type: "boolean", hasFileUpload: true },
      { name: "Internal Signage", type: "boolean", hasFileUpload: true },
      { name: "Wayfinding Signage", type: "boolean" },
      { name: "Signage Supplier", type: "text" },
      { name: "Signage Notes", type: "textarea" },
    ],
  },
  {
    name: "Documents & Attachments",
    owner: "",
    fields: [
      { name: "General Documents", type: "file", description: "Upload any additional documents here" },
      { name: "Contracts", type: "file" },
      { name: "Invoices", type: "file" },
      { name: "Certificates", type: "file" },
      { name: "Photos", type: "file" },
      { name: "Capital Raise Documents", type: "file", description: "Progress claims, deposits, etc." },
      { name: "Other Attachments", type: "file" },
    ],
  },
];

export function getDefaultItemsForSection(section: FormSection): Array<{
  field_name: string;
  field_type: string;
  field_options: Record<string, unknown> | null;
}> {
  return section.fields.map((field) => ({
    field_name: field.name,
    field_type: field.type,
    field_options: {
      options: field.options || null,
      placeholder: field.placeholder || null,
      description: field.description || null,
      hasFileUpload: field.hasFileUpload || false,
    },
  }));
}
